#配置服务器接口
server:
  port: 8888



spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


#配置maven
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#配置mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      #设置自增主键id
      id-type: auto

      #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





